#!/bin/bash

export SCRIPT_DIR=$(dirname "$0")

##
## Configuration Variables
##

SCHEMES="$@"

config ()
{
    # The workspace to build.
    #
    # If not set and no workspace is found, the -workspace flag will not be
    # passed in.
    #
    # Only one of `XCWORKSPACE` and `XCODEPROJ` needs to be set. The former will
    # take precedence.
    : ${XCWORKSPACE=$(find_pattern "*.xcworkspace")}

    # The project to build.
    #
    # If not set and no project is found, the -project flag will not be passed
    # in.
    #
    # Only one of `XCWORKSPACE` and `XCODEPROJ` needs to be set. The former will
    # take precedence.
    : ${XCODEPROJ=$(find_pattern "*.xcodeproj")}

    # A bootstrap script to run before building.
    #
    # If this file does not exist, it is not considered an error.
    : ${BOOTSTRAP="$SCRIPT_DIR/bootstrap"}

    # Extra options to pass.
    : ${BUILD_OPTIONS="RUN_CLANG_STATIC_ANALYZER=NO"}

    # A whitespace-separated list of default schemes to build.
    #
    # Individual names can be quoted to avoid word splitting.
    : ${SCHEMES:="'OctoKit Mac' 'OctoKit iOS'"}

    export XCWORKSPACE
    export XCODEPROJ
    export BOOTSTRAP
    export BUILD_OPTIONS
    export SCHEMES
}

##
## Build Process
##

main ()
{
    config

    if [ -f "$BOOTSTRAP" ]
    then
        echo "*** Bootstrapping..."
        "$BOOTSTRAP" || exit $?
    fi

    echo "*** The following schemes will be built:"
    echo "$SCHEMES" | xargs -n 1 echo "  "
    echo

    echo "$SCHEMES" | xargs -n 1 | (
        local status=0

        while read scheme
        do
            build_scheme "$scheme" || status=1
        done

        exit $status
    )
}

find_pattern ()
{
    ls -d $1 2>/dev/null | head -n 1
}

run_xcodebuild ()
{
    if [ -n "$XCWORKSPACE" ]
    then
        xcodebuild -workspace "$XCWORKSPACE" $BUILD_OPTIONS "$@" 2>&1
    elif [ -n "$XCODEPROJ" ]
    then
        xcodebuild -project "$XCODEPROJ" $BUILD_OPTIONS "$@" 2>&1
    else
        echo "*** No workspace or project file found."
        exit 1
    fi
}

build_scheme ()
{
    local scheme=$1

    echo "*** Cleaning $scheme..."
    run_xcodebuild -scheme "$scheme" clean >/dev/null || exit $?

    echo "*** Building and testing $scheme..."
    echo

    run_xcodebuild -scheme "$scheme" test
    local status=$?

    if [ "$status" -eq "66" ]
    then
        # Unit tests probably aren't supported.
        run_xcodebuild -scheme "$scheme" build
        status=$?
    fi

    return "$status"
}

export -f build_scheme
export -f run_xcodebuild

main
